--liquibase formatted sql

--changeset pedro.tenorio:1

CREATE TABLE app_user
(
    id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username          VARCHAR(255) NOT NULL UNIQUE,
    password          VARCHAR(255),
    name              VARCHAR(255),
    email             VARCHAR(255) NOT NULL UNIQUE,
    created_date      TIMESTAMP,
    last_updated_date TIMESTAMP
);

CREATE TABLE trainingSession
(
    id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    days              BIGINT,
    name              VARCHAR(255),
    created_date      TIMESTAMP,
    last_updated_date TIMESTAMP,
    user_id           BIGINT
);

ALTER TABLE trainingSession
    ADD CONSTRAINT FK_user_id FOREIGN KEY (user_id) REFERENCES app_user;